### ISSUE TITLE
Resolution Error

### ISSUE THREAD

**Issue by c-mattio** [DotModGroup/ColdWaters-DotMod#100]
When accessing menu options and then attempting to return to main menu, I get this crash:

![Dotmod error](https://user-images.githubusercontent.com/107951947/174873030-371a07d3-737e-49b4-9ed9-2096fdfb9254.jpg)

This is using the most recent update 0.3c

I have tried changing to other resolutions with none working.

[output_log.txt](https://github.com/DotModGroup/ColdWaters-DotMod/files/8951917/output_log.txt)

**Comment by FirebarSim** [comment]
This has been seen once before. The resolution steps were:

1. I removed mod, Cold Waters and all related folders
2. I made clean instalation of newest Graphics Card drivers
3. I made new CW install
4. Installed DotMod

Can you try this and report back?

**Comment by c-mattio** [comment]
Actually, I managed to fix it last night.

All I was remove DotMod via JSGME, downloaded and installed the bleeding edge version and then re-added it via JSGME.

Its now working fine.

I had done this with both version 0.3b and 0.3c so not sure if there is a fix in the bleeding edge version or I did something funky beforehand.
