### ISSUE TITLE
Error in 1984 Soviet Campaign with UK RN DDG type 42 incorrectly listed as FFG type 42

### ISSUE THREAD

**Issue by MurfdaSurf** [DotModGroup/ColdWaters-DotMod#101]
The following error code comes up in the 1984 Soviet Campaign

GetShipID not found: uk_84_ffg_type42

The ship is correctly listed as uk_84_ddg_type42

Looking at the mission text files I found the error in campaign004/missions/CARRER_STRIKE_1.txt 
line 29

**Comment by FirebarSim** [comment]
Thankyou, this will be fixed in the next release of the mod.
