### ISSUE TITLE
Weapons mounted on Helo are not returned to storage when stowing the helo

### ISSUE THREAD

**Issue by vothka** [DotModGroup/ColdWaters-DotMod#105]
You can just put your torps remaining to 0 by putlling your helo on the heli pad and stowing it again (and repeat)
The weapons are not returned to the ammo rack each time.

That also means if your helo returns after a mission with 0 weapons left - it will rearm when landing and you will lose these newly rearmed weapons if you stow the helo

**Comment by FirebarSim** [comment]
I have been unable to replicate this, what are the conditions you experience this under. I.e. ship, helo, campaign, or Mission.

**Comment by FirebarSim** [comment]
Hi, this turned out to be a slightly weird bug in the code that I think I have now fixed. Should be closed when 0.4a-2 is uploaded.
