### ISSUE TITLE
In dot mod 0.4a. The model of helicopter SH-34J/WESSEX, appears flying "back"

### ISSUE THREAD

**Issue by TORDO222** [DotModGroup/ColdWaters-DotMod#106]
Problem in dot mod 0.4a. The model of helicopter SH-34J/WESSEX, appears flying "back". That is, the tail rotor in the direction of movement. The rest of the helicopters, are presented and move in the right way. Greetings

**Comment by FirebarSim** [comment]
Appears that there is an incorrect rotation in the Mesh for the main body. @RedEagle32 to fix unless there proves to be a larger underlying issue.

**Comment by TORDO222** [comment]
Good!. Thanks in advance!. Greetings!

**Comment by RedEagle32** [comment]
Hello, I have located the problem, I will look for a fix, will let you know how I get on

**Comment by RedEagle32** [comment]
I have fixed it, an update should be out soon

**Comment by HobbitJack** [comment]
Fix has been uploaded to the Dev Repo.

**Comment by TORDO222** [comment]
Great job!. Greetings!
