### ISSUE TITLE
in dot mod 0.4 have error: unable to get sprite from: hud/damage_control/aus_99_ffg_adelaide_pl.png

### ISSUE THREAD

**Issue by thanos7468** [DotModGroup/ColdWaters-DotMod#107]
![image](https://user-images.githubusercontent.com/109855886/180605254-dc68be5a-6f4b-4aa9-a5e7-95ec62f0e74f.png)

**Comment by FirebarSim** [comment]
I think that we have seen people have this issue before, please try deleting the dotmod folder and then reinstalling the mod.

If that doesnt fix it please reopen the issue.
