### ISSUE TITLE
Cannot Fix Damaged Systems in Port During Campaign

### ISSUE THREAD

**Issue by ImperialCenter000** [DotModGroup/ColdWaters-DotMod#108]
Double-clicking on damaged system while in port does nothing.  Text appears fuzzy, as if double-overlayed.

**Comment by FirebarSim** [comment]
This issue should now be fixed in a hotfix of 0.4a-2, please update the game files to fix.

**Comment by ImperialCenter000** [comment]
Great, thanks!
