### ISSUE TITLE
Invalid method with Trafalgar Class in 0.4

### ISSUE THREAD

**Issue by lesrae69** [DotModGroup/ColdWaters-DotMod#112]
![image](https://user-images.githubusercontent.com/110280669/181880576-251b5845-ffed-43c8-8ed4-961e2c0828b0.png)

**Comment by FirebarSim** [comment]
This is because your dotmod folder was not overwritten on install. Delete the dotmod folder from StreamingAssets and then reinstall the mod and it should all work.

Please reopen if this does not solve.
