### ISSUE TITLE
Game constantly bugs when on inserting special forces into Narvik in the 1984 USSR Campaign

### ISSUE THREAD

**Issue by Charles98k** [DotModGroup/ColdWaters-DotMod#118]
![image](https://user-images.githubusercontent.com/110731710/183253305-6fb510b4-88c8-4124-8e2d-6fa7f47239a1.png)

**Comment by mhj1992** [comment]
I get the exact same error when doing a land strike with a Kirov on 84. Assigned multiple times during campaign, and the issue stays the same. Tried twice each time.

**Comment by HobbitJack** [comment]
Please include an output_log.txt.

**Comment by MasterTurtle240** [comment]
[output_log.txt](https://github.com/DotModGroup/ColdWaters-DotMod/files/9760966/output_log.txt)
 I am having the same issue here is mine

**Comment by HobbitJack** [comment]
Issue has been solved in dev.
