### ISSUE TITLE
i get an IndexOutOfRangeException: Array index is out of range error every time i try to fire a torpedo

### ISSUE THREAD

**Issue by RedBaron521** [DotModGroup/ColdWaters-DotMod#124]
IndexOutOfRangeException: Array index is out of range

PlayerFunctions.GetPlayerTorpedoIDInTube (Int32 Tube)
PortRearm.SetLoadoutStats ()
WeaponSource.FireTube ()
PlayerFunctions.Update ()

**Comment by HobbitJack** [comment]
Please include an output_log.txt.

**Comment by RedBaron521** [comment]
oh yeah, sorry , forgott about it ^^
[output_log.txt](https://github.com/DotModGroup/ColdWaters-DotMod/files/9336967/output_log.txt)

**Comment by RedBaron521** [comment]
I think i know the source of the problem now: I think a third-party Programm, i thought i had closed, interfered with the game and produced the error, If that's the case, i'm truly sorry to have wastet your time.
