### ISSUE TITLE
Kashin-class DDG unplayable?

### ISSUE THREAD

**Issue by faiprussia** [DotModGroup/ColdWaters-DotMod#128]
Greetings.
Dear DotMod modders.

I want to ask a question, why does Kashin class DDG unplayable in the campaign? I think the ship's weapons (shown in the 3D model) are good enough for the campaign. Is it because the vanilla game's program disables the ship's missile system, guns, and torpedoes?
I hope my question doesn't offend you. I really can't wait for the next update cuz Sea Powers will come in a pretty long time despite being confirmed released in 2023. 

Thank you.
![BANJOE ADEM](https://user-images.githubusercontent.com/111725220/185844685-47c80e1a-bb20-4a84-9d67-d48d5403886c.jpg)

**Comment by HobbitJack** [comment]
Not all vessels are always ready for player/campaign use. The Kashin will be made playable in the campaign for the next mod release.
