### ISSUE TITLE
ERROR:Weaponname usn_mk37 not found

### ISSUE THREAD

**Issue by Ghsotlydoggo** [DotModGroup/ColdWaters-DotMod#130]
When I launch the exe to start cold waters I cannot get to the main menu without this popping up. I've done multiple installs and I always get the same error message. From what i can tell all the files are there.

**Comment by Ghsotlydoggo** [comment]
[output_log.txt](https://github.com/DotModGroup/ColdWaters-DotMod/files/9578236/output_log.txt)

**Comment by TORDO222** [comment]
Attention to developers: Issues reports 130 and 132 refer to a probable corrupted data in the mod. Evidence of hack??

**Comment by HobbitJack** [comment]
This issue is caused by improper installation. Closed.
