### ISSUE TITLE
InvalidOperationException when inserting a SEAL team near Archangelsk

### ISSUE THREAD

**Issue by Andrzej597** [DotModGroup/ColdWaters-DotMod#137]
Got such errors when trying to insert a SEAL team to Archangelsk:
![image](https://user-images.githubusercontent.com/33331189/197223066-dd40bab7-a0b9-446a-a0ac-b371aa6d9529.png)

**Comment by HobbitJack** [comment]
Known issue involving certain ports. Will be looked into for the next release.

**Comment by HobbitJack** [comment]
Issue has been solved in dev.
