### ISSUE TITLE
NT37C Torpedo not affected by noisemakers and knuckles

### ISSUE THREAD

**Issue by Letome1** [DotModGroup/ColdWaters-DotMod#141]
Brand new soivet 1984 campaign fighting against Zwaardvis and the only thing I can do in my Kotlin is to run away. I did attempted different methods of noise makers and knuckle combinations but the torpedo goes straight for me.

**Comment by HobbitJack** [comment]
This is intended behavior because the NT37C torpedo is wire-guided. Closed.
