### ISSUE TITLE
Playable Helicopters from surface ships have no torpedoes?

### ISSUE THREAD

**Issue by hammer2019** [DotModGroup/ColdWaters-DotMod#143]
even with land on mother ship no change !
what's the matter? 

also i have a few missile change in Ticonderoga  is that related ?  if is whats is solution !??

**Comment by HobbitJack** [comment]
Please include a screenshot of your game with the problem.

**Comment by HobbitJack** [comment]
Issue closed as likely caused by improperly set up vessel files.
