### ISSUE TITLE
The foil tail of the Grisha III FFG can't be repaired in port

### ISSUE THREAD

**Issue by TetrisDuTrou** [DotModGroup/ColdWaters-DotMod#145]
![image](https://user-images.githubusercontent.com/72306596/216972020-87c672a8-c0e4-46dd-b5f4-e4c42849a6fe.png)
It isn't present in the damage control window and once it's broken nothing can be done.

**Comment by TetrisDuTrou** [comment]
Using the "next" and "previous" buttons doesn't help.

**Comment by HobbitJack** [comment]
This issue has been fixed, and the fix will be included in v0.5 of the mod.
