### ISSUE TITLE
InvalidOperationException Arkangelsk and Narvik Insertion

### ISSUE THREAD

**Issue by FirebarSim** [DotModGroup/ColdWaters-DotMod#146]
![image](https://user-images.githubusercontent.com/32907623/223531045-8cefade5-5e00-4a1b-ad9a-e1be2f2ccd21.png)

**Comment by HobbitJack** [comment]
Duplicate of #118, leaving for clerical purposes.

**Comment by HobbitJack** [comment]
Issue has been solved in dev.
