### ISSUE TITLE
ERROR: weaponName usn_mk46_84 not found

### ISSUE THREAD

**Issue by gorsbren** [DotModGroup/ColdWaters-DotMod#147]
Just downloaded and installed dotmod and activated it and this error pops up.

Try Continue just sits there and won't load the game.

Any ideas on how to fix?

**Comment by HobbitJack** [comment]
As this issue is not seemingly present in most installs of the game, please attempt a complete re-installation of the mod on a fresh copy of the game, and if that does not work, please include details about your computer's setup.

**Comment by HobbitJack** [comment]
Closed as is likely a local issue.
