### ISSUE TITLE
I don't know where to put the modified texture

### ISSUE THREAD

**Issue by ponitora** [DotModGroup/ColdWaters-DotMod#148]
I love this game and want to give credit to the creator of dotmod.

By the way, I liked the Seawolf class in this game, and enjoyed modifying the textures myself.
But after installing dotmod, I don't know where to put my seawolf textures. I tried various things and put it in various places, but it is not reflected. if you'd kindly teach me. Where should I put it?

I don't even know where the Virginia-class and Io Jima textures are. What folder are these textures in?

**Comment by HobbitJack** [comment]
A GitHub issue is not the correct place to address this. These files are contained in the various AssetBundles included in the mod. Please reach out to us on our GitHub for more detailed information on accessing these resources.
