### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Wolf347** [DotModGroup/ColdWaters-DotMod#154]
found a error on the mod the Dotmod. 
![Screenshot 2023-09-13 092626](https://github.com/DotModGroup/ColdWaters-DotMod/assets/144920499/8c811820-7f51-4b47-b3cd-43b85f66c527)

**Comment by HobbitJack** [comment]
Please re-install your game fresh by manually deleting it from File Explorer and then re-installing the game through Steam. Then, re-install the mod as before. If the issue persists, please come to our Discord for tech support.
