### ISSUE TITLE
GetShipID not found: knm_84_ss_kobben

### ISSUE THREAD

**Issue by wellers** [DotModGroup/ColdWaters-DotMod#155]
Hi DotMod team, only recently got into Cold Waters and playing with DotMod. 

Loving the work you guys are doing and hope you continue to add updates.

I've been playing the Soviet 1984 Campaign and occasionally get the following error:
![image](https://github.com/DotModGroup/ColdWaters-DotMod/assets/19975962/a594ffbb-1ac3-4283-8c51-e10c8e758922)

I think the cause could be this line here:
https://github.com/DotModGroup/ColdWaters-DotMod/blob/e4759a09b0287bcf10fa05ad83fef64df7a9b38a/ColdWaters_Data/StreamingAssets/dotmod/campaign/campaign004/vessel_selector.txt#L45C56-L45C56

`knm_84_ss_kobben` is referenced but I think this should be `knm_68_ss_kobben`.

**Comment by HobbitJack** [comment]
Known issue which has already been fixed in the developer build.
