### ISSUE TITLE
Ballistic missiles for Delta III and IV class and Typhoon

### ISSUE THREAD

**Issue by herjaniceland** [DotModGroup/ColdWaters-DotMod#157]
Hello there.

I have been trying out dot mod and must say it is really nice. Looks and sounds more realistic than the original game.

I want to add one idea. Would it not be interesting if you are able to shoot out ballistic missiles with Russians Delta III, Delta IV and Typhoon class submarines since their main weapon is missiles? Would make the game more realistic.
You can do so with Yankee class.

All the best.

**Comment by HobbitJack** [comment]
This is planned for version v0.5.
