### ISSUE TITLE
Error loading a save game

### ISSUE THREAD

**Issue by herjaniceland** [DotModGroup/ColdWaters-DotMod#158]
Good day.

Trying to load a saved campaign from NATO 1984 this happened:

The Following Error has Ocurred:

NulllReferenceException
Unity.Engine.Transform.get_position ()
Submarine.Marker.LateUpdate ()

Trying to continue but nothing happens.

All the best

**Comment by HobbitJack** [comment]
Added before, but closed as duplicate of #162.
