### ISSUE TITLE
USSR North Atlantic Campaign Kirov CGN

### ISSUE THREAD

**Issue by grumpsdad** [DotModGroup/ColdWaters-DotMod#161]
![Screenshot 2023-10-27 093803](https://github.com/DotModGroup/ColdWaters-DotMod/assets/149174768/e8eb2673-1e7d-49d5-bf39-66466ff2ab1c)

**Comment by grumpsdad** [comment]
During the campaign there is a mission to do a missile strike on Narvik.  When trying to enter the Narvik area of the map the above error displays and will not  let you continue.

**Comment by HobbitJack** [comment]
Issue has been solved in release.
