### ISSUE TITLE
File validation failed

### ISSUE THREAD

**Issue by 777xRaptor** [DotModGroup/ColdWaters-DotMod#163]
After succesfully installing and activating dotmod for Cold Waters, when starting up the game, the following message appears:
"File validation failed due to non-vanilla file at path: \globalgamemanagers. The application will now exit."

I don't know what's wrong here since the mod shouldn't change this file in the first place. However, the vanilla game version runs as intended and doesn't crash upon startup or while playing.

**Comment by HobbitJack** [comment]
You are using a pirated copy of Cold Waters. We do not support pirated copies of the game.
