### ISSUE TITLE
DotModInstaller.exe contains malware?

### ISSUE THREAD

**Issue by thrombozytenaggregationshemmer** [DotModGroup/ColdWaters-DotMod#164]
Serveral AV scanners show this file malicious.

**Comment by HobbitJack** [comment]
Known issue. The compiler Nuitka often gets flagged as false positive. Steps have been taken to avoid this where possible, however without spending an absorbent amount of money this is not something which can be solved. The installer is compiled directly from the source code included in the repository, or a manual installation can be performed.
