### ISSUE TITLE
File validation failed due to non-vanilla file path

### ISSUE THREAD

**Issue by Nitrofish** [DotModGroup/ColdWaters-DotMod#167]
I've installed the mod, but every time I start up the game the loading screen starts but then displays the message below then quits. 

"File validation failed due to non-vanilla file path: \globalmanagers. The application will now quit." 

I obviously do not have the game installed in the default location, but entered the right location during the install when prompted.

**Comment by HobbitJack** [comment]
DotMod does not support pirated copies of Cold Waters. Please purchase the game on Steam or GoG.
