### ISSUE TITLE
Training scenario Navigation crash while loading

### ISSUE THREAD

**Issue by xavnl** [DotModGroup/ColdWaters-DotMod#170]
Scenario sent an error after pressing battle station. Scenario played without a problem though.
![Screenshot (86)](https://github.com/DotModGroup/ColdWaters-DotMod/assets/7201790/cdc04780-d1b3-436d-a997-35d8bcdb714d)

**Comment by HobbitJack** [comment]
Issue is probably not related to training scenarios, but the training scenarios are unsupported with DotMod.
