### ISSUE TITLE
Bug: IndexOutOfRangeException

### ISSUE THREAD

**Issue by Bratsakia** [DotModGroup/ColdWaters-DotMod#56]
Dotmod 0.2a VS210830F

Reloading a NATO 1984 North Atlantic Campaign to resume it (no change to the game/mod since started it). 

Sailing east to "patrol area blue043". 

Error screen : "IndexOutOfRangeException : Array Index is out of range"

Impossible to continue ("Try to continue" button doesn't leave the error page). Forced to "close game (safe option)".

Attacing save file (original default name) :

[colorCyanNATONorthAtlantic1984colorSAVE.zip](https://github.com/Dot-M134/ColdWaters-DotMod/files/7317447/colorCyanNATONorthAtlantic1984colorSAVE.zip)

**Comment by Bratsakia** [comment]
Also, output log :

[output_log.txt](https://github.com/Dot-M134/ColdWaters-DotMod/files/7317520/output_log.txt)

**Comment by HobbitJack** [comment]
Did you recently update Bleeding Edge version? I did a commit yesterday that fixed some issues but would've broken save files.

**Comment by Bratsakia** [comment]
No, I installed DotMod three weeks ago, and haven't touched the files since.

Also, for what it's worth, the bug appeared on a mission to prevent some resupply. I see on the "closed issues" list that people also got an IndexOutOfRangeException in the same situation. Could it be the same bug somehow reappearing ?
