### ISSUE TITLE
Trafalgar issues

### ISSUE THREAD

**Issue by Stallfighter** [DotModGroup/ColdWaters-DotMod#57]
1) Towed array attachment
https://media.discordapp.net/attachments/866120539512373268/898734884640669706/unknown.png?width=420&height=382
2) Sound source for her screw is located near center rather then in screw itself
3) Soviet submarine on wired torpedo picture.
https://media.discordapp.net/attachments/866120539512373268/898737738667393074/unknown.png

**Comment by FirebarSim** [comment]
Only one of the 3 issues was fixed.
