### ISSUE TITLE
*68 Oberon either have too many torpedoes or in need of the stern tubes

### ISSUE THREAD

**Issue by Stallfighter** [DotModGroup/ColdWaters-DotMod#67]
As with *84 Oberon, there are 22 torpedoes, but it takes into account 4 from stern tubes, which is not set yet. So, it should either have 18 torpedoes total or 22 but with stern tubes.

**Comment by Stallfighter** [comment]
Also, in the description said 2 stern tubes are stated to be non-reloadable despite they in fact were.

**Comment by dimitargslavchev** [comment]
> Also, in the description said 2 stern tubes are stated to be non-reloadable despite they in fact were.

Submarines can't transport torpedoes from the stern tubes/supply to the forward tubes/supply. Also some russian submarines have the 53 cm and the 65 cm torpedoes in different compartments too.

I don't think that the game is able to do any of that.
