### ISSUE TITLE
Arithmetic Exception: NAN

### ISSUE THREAD

**Issue by FeydRautha69** [DotModGroup/ColdWaters-DotMod#70]
Individual mission, had launched a few torps at an alpha, the game went boom
![boom](https://user-images.githubusercontent.com/97259735/148457920-26265498-c034-49f2-a5cc-e9d624de3a47.png)
[output_log.txt](https://github.com/DotModGroup/ColdWaters-DotMod/files/7824955/output_log.txt)

**Comment by FeydRautha69** [comment]
And again.....just started using this mod, is it really this buggy????

[output_log.txt](https://github.com/DotModGroup/ColdWaters-DotMod/files/7825160/output_log.txt)

**Comment by HobbitJack** [comment]
Duplicate of #51, but we'll certainly look at it.
