### ISSUE TITLE
Issue upon loading/stuck on loading

### ISSUE THREAD

**Issue by cdodders** [DotModGroup/ColdWaters-DotMod#73]
Get an issue where it flashes up in red that it cannot find a file name for a torpedo, I click continue to try and keep loading but it's stuck on LoadingVesselData:usn_04_ssn_Virginia

![image](https://user-images.githubusercontent.com/30770566/151837971-28319115-ac92-4373-ac41-711aef45093e.png)

**Comment by HobbitJack** [comment]
Issue has been fixed in a release since, so I am told.
