### ISSUE TITLE
ArgumentOutOfRangeException: Argument is out of range.

### ISSUE THREAD

**Issue by LukeV1** [DotModGroup/ColdWaters-DotMod#75]
I am currently playing the `NATONorthAtlantic1968` Campaign. My Mission is "Sink ASW patrols and aircraft carrier". Tried two times now, but the mission crashes at some point with _different_ errors. Unfortunately the first log file was overwritten so I just got my 2. attempt on file.

Maybe you can take a look at it?
Thanks!
[output_log.txt](https://github.com/DotModGroup/ColdWaters-DotMod/files/8148346/output_log.txt)

**Comment by FirebarSim** [comment]
This appears to be a bug in the Damage Control system at first glance. Were you able to click through the error message? And are you able to try and recreate with the Debug Level in the Options Menu set to All?

**Comment by LukeV1** [comment]
Hi, thanks for looking into this!

I could click on the error message but the game didn't recover. I can't recall wheter it froze or crashed completely but there was no way to continue for sure.

Today I changed the debug level and tried again - and guess what: this time it didn't crash. I'll try it again soon :P

**Comment by FirebarSim** [comment]
Thanks, let me know if it occurs again, I am trying to track these down slowly but a lot is dependent on if I can recreate!

**Comment by HobbitJack** [comment]
No updates recently, so closing with unreproduceable for now. Feel free to open if more info is procured.
