### ISSUE TITLE
game wont load due to error

### ISSUE THREAD

**Issue by Bismarck2206** [DotModGroup/ColdWaters-DotMod#77]
![20220306093616_1](https://user-images.githubusercontent.com/101056320/156930408-7713522f-01e3-41c7-9acf-7b3371b9def3.jpg)
not sure how to fix this, would love to get this fixed

**Comment by FirebarSim** [comment]
Have you previously had EpicMod installed? Try deleting (or renaming if you want to keep it) the override folder and see if the game loads. Aps-124 doesnt look like one of our sensors.

**Comment by Bismarck2206** [comment]
i did, thanks for the help i just did a clean install of cold waters and fixed the issue. I completely forgot i installed EpicMod at one point
