### ISSUE TITLE
Kilo telegraphs speeds

### ISSUE THREAD

**Issue by dimitargslavchev** [DotModGroup/ColdWaters-DotMod#79]
I noticed that the Kilo telegraphs speeds are different from other diesel-electric subs:

```
Kilo:   3, 6, 8, 12, 17
Others: 3, 5, 8, 10, MAX
```

**Comment by FirebarSim** [comment]
This is due to the Kilo class having a higher top speed I believe. I don't think this is actually an issue but please reopen if it proves to be.

**Comment by dimitargslavchev** [comment]
Not really an issue, of course. You can put speed in knot directly.  I remember that earlier there was a large discrepancy in telegraph speeds for the diesel electrics and they were brought up to the same.  
  If it is due to speed, the Julliet is even faster at 18 knots.
 







 >-------- Оригинално писмо --------

 >От: FirebarSim ***@***.***

 >Относно: Re: [DotModGroup/ColdWaters-DotMod] Kilo telegraphs speeds (Issue
 #79)

 >До: DotModGroup/ColdWaters-DotMod  

 >Изпратено на: 17.04.2022 16:33



 
 
  
  
  
This is due to the Kilo class having a higher top speed I believe. I don't think this is actually an issue but please reopen if it proves to be.
