### ISSUE TITLE
Reactor SCRAM every couple of minutes on Los Angeles in NATO North Atlantic 1984, 1st mission

### ISSUE THREAD

**Issue by fhare666** [DotModGroup/ColdWaters-DotMod#81]
I keep getting regular (every 2-3m) reactor scrams using the Los Angeles class on the first mission of the NATO North Atlantic 1984 campaign.

I have:

uninstalled and reinstalled latest version of dotmod
uninstalled dotmod, uninstalled cold waters and re-installed both

I also have seen several of the red screen "try to continues" at various places.

I am running Cold Waters v.1.15g from Steam on PC
DotMod v 0.3b-3 Script VS220318F
Windows 10 PC fully patched
Nvidia GeForce 472.98 drivers

 Any help appreciated.

**Comment by FirebarSim** [comment]
This sounds like EpicMod leftovers still. Try killing off the config settings file in AppData C:\Users\[USERNAME]\AppData\LocalLow\Killerfish Games\Cold Waters and make sure that the epicmod override folder is definitely removed from StreamingAssets

**Comment by fhare666** [comment]
FirebarSim thanks clearing out that EpicMod turd and re-installing did the trick. Thanks a lot!

**Comment by FirebarSim** [comment]
Glad to hear it sorted things! Let us know if you have more issues.
