### ISSUE TITLE
Expose towed array durability or speed threshold values via string/variable on item in sensor.txt or vessel.txt

### ISSUE THREAD

**Issue by Shaggygoblin** [DotModGroup/ColdWaters-DotMod#84]
trying to find info on towed array values for speed or durability(?) to fit with a custom sub (silent speed is 12kts). even when at 5kts, deploying towed array usually insta-breaks it (repair in port).  Do I really need to go the route of dnspy'ing the Assembly-CSharp.dll to find and/or tweak the necessary values to make towed array's at a minimum as durable as torpedo wires?

The closest thing I've been able to find on the topic is this: 
- Towed sonar arrays may have custom speed parameters for optimum tow speed and never exceed speed.

From this mod:
https://github.com/archer884/ColdWatersEnhanced

I just want to not have to RTB to repair after every encounter because the TA dies at mission start when I deploy it at 5kt.

If this is unfeasible for whatever reason, please elaborate.

**Comment by HobbitJack** [comment]
The tail isn't supposed to break at 5 knots. Double-check you don't have any Epic Mod assets because that sounds like one of our little safeguards, but I'm not entirely sure. The Towed Array is supposed to be stable up to 15 knots.

**Comment by Shaggygoblin** [comment]
> Double-check you don't have any Epic Mod assets...

I thought of that after reading some other issues where it was mentioned that EM can leave remnants.
Found DM and EM when looking for mods. Also read many things about the controversy.
I have never used EM, but I think I had DM 3a and recently removed it and added 3b.

This is a clean install of CW and DM.
Using 3b.
Will scrub them and reinstall again to see if that sorts it, then reply accordingly.

**Comment by Shaggygoblin** [comment]
Fresh install of CW and 3b-4: 6 encounters initiated at patrol (5knts) at 50', TA deployed fine.
Even got it to 15knts a few times with no breakage.  Didn't chance going faster while deployed.
On the 7th encounter, at patrol (5knts), running silent at 50' depth, TA broke on deploy.
Went to port, repaired.
8th encounter, patrol, silent at 50', TA broke on deploy.
Port, fix, leave.
9th encounter started at 30knts, 600' depth. Went silent, set turns to 3knts, stayed 600'.  At 3knts and 600', TA broke on deploy.

Will Uninstall/Scrub and try again tonight or tomorrow.

I will see if I can get it to do it again.  Which logging options do I need to enable for a useful log in this instance?

**Comment by HobbitJack** [comment]
Can't deploy the tail at PD. It snaps in the turbulence. If you deploy it below 5 knots, it'll sink into your propshaft, and that ends about as well as you'd imagine.

**Comment by HobbitJack** [comment]
Closing.

**Comment by Shaggygoblin** [comment]
Thank you for that. Please consider adding these particular details to the "How to DotMod" readme.  As the Vanilla play of "It's just there and automatic" and DotMod are so night and day different that it should be prominently covered but is merely mentioned as "Deployable Towed array - use Backspace to toggle" (paraphrasing based on what's written and gathered knowledge from further exploratory searching/reading).  Depths/Speed when-to and when-not-to should be at least touched on for us peeps that may be new to CW and/or at least new to Mods for it, and chose DM as the 'test the waters' mod to use.
In my minds eye, I don't recall seeing anything about the specifics of TA's in researching additions/bring-overs from EM either.
In that, as I understand it, many things which were EM first, were brought to DM, but they're apparently implied with no instruction because we should just know how based on prior EM experience.  As mentioned before, I have never "EM'd".

Again, thank you for the insights.  Keep up the awesome work!

**Comment by Shaggygoblin** [comment]
On reconsidering the totality of the issue and taking in the context, there are still issue.
Please reopen.

https://github.com/DotModGroup/ColdWaters-DotMod/issues/84#issue-1206506262
> ...custom sub (silent speed is 12kts). even when at 5kts, deploying towed array usually insta-breaks it (repair in port).

> find and/or tweak the necessary values to make towed array's at a minimum as durable as torpedo wires?

[https://github.com/DotModGroup/ColdWaters-DotMod/issues/84#issuecomment-1100969064](url)
> The tail isn't supposed to break at 5 knots.

https://github.com/DotModGroup/ColdWaters-DotMod/issues/84#issuecomment-1104494868
> Can't deploy the tail at PD. It snaps in the turbulence. If you deploy it below 5 knots, it'll sink into your propshaft, and that ends about as well as you'd imagine.


https://github.com/DotModGroup/ColdWaters-DotMod/issues/84#issuecomment-1101467725
> Fresh install of CW and 3b-4: **6 encounters initiated at patrol (5knts) at 50', TA deployed fine.**
> 9th encounter started at 30knts, 600' depth. Went silent, set turns to 3knts, stayed 600'. At 3knts and 600', TA broke on deploy.

Can't deploy at PD (patrol depth? ie 50'?) contradicts what i'm seeing.

Also, 3knts is not a one off. I started doing 3knts because it broke 'less frequently' than at 5knts. I thought that one was a chance based fluke of bad luck.
What you say implies it was a fluke run of good luck that I can deploy TA, successfuly, at 3knts more frequently than 5knts...

Also, where are the values/variables for the TA durability read from?

**Comment by FirebarSim** [comment]
Marking for further consideration when refreshing Towed Array code.

**Comment by FirebarSim** [comment]
As an aide memoir to myself 

I need to look at how the damage code is done for Towed Arrays to implement something similar for decoys. As I want to do surface ship towed arrays this is something to think on.

**Comment by Shaggygoblin** [comment]
just checking back in case of update to:
`where are the values/variables for the TA durability read from?`

**Comment by HobbitJack** [comment]
Towed array break chances are hardcoded.

**Comment by Shaggygoblin** [comment]
unfortunate. ty.

**Comment by FirebarSim** [comment]
Towed array and towed decoy break values will be exposed in vessel files at next update.

**Comment by Shaggygoblin** [comment]
Y'all are legend!!

**Comment by FirebarSim** [comment]
TowedArrayMaxSpeed and TowedArrayMinSpeed can now be set in a vessel file

**Comment by Shaggygoblin** [comment]
LEGEND !!
