### ISSUE TITLE
Unable to use Yasen - Mission Editor

### ISSUE THREAD

**Issue by el-murf** [DotModGroup/ColdWaters-DotMod#91]
pretty much what it says in the title. Attached image has the various errors. Have tried multiple things to see if the issue was unique to a certain set of parameters, including changing the type and number of opposing ships, the date, the location, weather, pretty much all the mission editor settings. such a cool boat and i am bummed not to be able to mess around with it
![Yasen Error SC](https://user-images.githubusercontent.com/104541269/167055493-b6f03a8d-0846-4e9a-9f92-3e2ec6065f94.png)

**Comment by HobbitJack** [comment]
The Severodvinsk class is still unplayable and will be removed fr the list of playable vessels on the next update until I get around to making it playable. School is, however, hitting hard right now.

**Comment by el-murf** [comment]
Thanks for the update! Good luck with school
