### ISSUE TITLE
After loading, no menu options work

### ISSUE THREAD

**Issue by srhSTOC** [DotModGroup/ColdWaters-DotMod#95]
Hi, after installing Dot mod, Cold Waters will load but when you click on any of the main menu options you get the below and you can't play the game. I tried a fresh install of the game but this didn't help. I've attached the output log which suggests there are some issues with files but thats as much as I could figure out! Thanks!
![image](https://user-images.githubusercontent.com/106347111/170558901-16c663d3-0268-4074-b05f-2bd4cb05928b.png)
[output_log.txt](https://github.com/DotModGroup/ColdWaters-DotMod/files/8781490/output_log.txt)

**Comment by HobbitJack** [comment]
Please include an output_log.txt.

**Comment by srhSTOC** [comment]
Hi, I think that file is attached below the image.

**Comment by Alpha22g** [comment]
The same happens to me...  in the loading screen it says: "plan_fr_20_ssn_suffren_un..."

**Comment by HobbitJack** [comment]
> Hi, I think that file is attached below the image.

Yup... I'm blind, as usual! Thanks, and sorry 'bout that.

**Comment by HobbitJack** [comment]
> The same happens to me... in the loading screen it says: "plan_fr_20_ssn_suffren_un..."

That sounds like an issue due to having Epic Mod leftovers somehow, since we don't do anything French related (yet).

**Comment by Alpha22g** [comment]
Thanks!

**Comment by FirebarSim** [comment]
May be the same as #90

**Comment by McLaski** [comment]
Double checked this issue on a fresh installation with DotMod v0.3c-1. It is not there. Everything is fine and works as intented with DotMod v0.3c-1.

**Comment by FirebarSim** [comment]
Thanks I'll investigate and see if I can fix it. Clearly what I tried either failed or got missed from the build.

**Comment by HobbitJack** [comment]
No new report in over a year, likely solved in update(s).
