### ISSUE TITLE
Occurred error logging the game after download: " GetDepthWeaponID not found : usn_9x3_mk-7_shell "

### ISSUE THREAD

**Issue by Alpha22g** [DotModGroup/ColdWaters-DotMod#96]
Hi, I got this error logging the first time in the game after downloading the mod, I have already redownloaded the mod and the game but it still occurs. How can I fix this. Thanks for the help !

**Comment by HobbitJack** [comment]
Please include an output_log.txt and a screenshot of the stack trace in-game.

**Comment by HobbitJack** [comment]
Closing due to no info for two months.
